# Generated by Django 5.2.17 on 2026-10-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="America/Chicago", max_length=64),
        ),
    ]
