# Generated by Django 5.2.17 on 2026-08-27 01:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Ramp-In", "Build", "Deload"', max_length=60)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True, default='', help_text='May include simple HTML like <strong>.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub', models.CharField(blank=True, default='', max_length=150)),
                ('flavor', models.CharField(blank=True, default='', max_length=250)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('amber', 'Amber'), ('violet', 'Violet'), ('teal', 'Teal'), ('rose', 'Rose')], default='red', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('Main', 'Main'), ('Core', 'Core'), ('Cardio', 'Cardio'), ('Stretch', 'Stretch')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('sets_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps_text', models.CharField(blank=True, default='', max_length=60)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('time_text', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_exercises', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.workout')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompletedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='training.exercise')),
            ],
            options={
                'unique_together': {('user', 'exercise', 'log_date', 'set_number')},
            },
        ),
        migrations.CreateModel(
            name='PhaseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=3)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.phase')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.workout')),
            ],
            options={
                'ordering': ['phase_id', 'id'],
                'unique_together': {('phase', 'weekday')},
            },
        ),
    ]
