# Generated by Django 5.2.17 on 2026-08-28 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_populate_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='workoutcompletion',
            name='phase',
        ),
        migrations.AlterField(
            model_name='week',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='training.phase'),
        ),
        migrations.AlterField(
            model_name='workoutcompletion',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_completions', to='training.week'),
        ),
        migrations.DeleteModel(
            name='PhaseDay',
        ),
    ]
