# Generated by Django 5.2.17 on 2026-08-28 02:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_phase_duration_weeks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutcompletion',
            unique_together={('user', 'log_date', 'workout')},
        ),
    ]
