# Generated by Django 5.2.17 on 2026-08-28 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_bootstrap_isaac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='training.plan'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='training.plan'),
        ),
    ]
