# Generated by Django 5.2.17 on 2026-08-28 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('training', '0011_backfill_client_and_plan_assignments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedset',
            unique_together={('client', 'exercise', 'log_date', 'set_number')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutcompletion',
            unique_together={('client', 'log_date', 'workout')},
        ),
        migrations.AlterField(
            model_name='completedset',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sets', to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='workoutcompletion',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_completions', to='accounts.client'),
        ),
        migrations.RemoveField(
            model_name='completedset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutcompletion',
            name='user',
        ),
    ]
