# Generated by Django 5.2.17 on 2026-08-29 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_completedset_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='source_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='training.plan'),
        ),
    ]
