# Generated by Django 5.2.17 on 2026-08-30 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_clone_shared_plans_into_client_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.CharField(blank=True, default='', help_text='e.g. "180g/day" or "5g"', max_length=100)),
                ('timing', models.CharField(blank=True, default='', help_text='e.g. "Morning" or "Post-workout"', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='training.plan')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.CharField(blank=True, default='', help_text='e.g. "180g/day" or "5g"', max_length=100)),
                ('timing', models.CharField(blank=True, default='', help_text='e.g. "Morning" or "Post-workout"', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='training.plan')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
