# Generated by Django 5.2.17 on 2026-10-01 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_timezone"),
        ("training", "0015_nutrient_supplement"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutcompletion",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutcompletion",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SyncEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=32)),
                ("target_key", models.CharField(max_length=120)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("applied", "Applied"), ("stale", "Stale")],
                        max_length=10,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_events",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client", "target_key", "-occurred_at"],
                        name="sync_target_latest",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "event_id"),
                        name="unique_sync_event_per_client",
                    )
                ],
            },
        ),
    ]
